name: Test
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Date From
        env:
          TZ: 'Asia/Tokyo'
        run: echo "DATE_FROM=$(date +'%Y-%m-%d' --date '7 day ago')" >> $GITHUB_ENV

      - name: Date To
        env:
          TZ: 'Asia/Tokyo'
        run: echo "DATE_TO=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Run
        uses: iwata-n/actions-slack-mining@main
        with:
          param: 'parameter'
          date_from: ${{ env.DATE_FROM }}
          date_to: ${{ env.DATE_TO }}
          group_mention: ${{ secrets.SLACK_GROUP }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_user_token: ${{ secrets.SLACK_USER_TOKEN }}
